
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

panel_custom:
  - name: pose-estimation-panel
    # url_path needs to be unique for each panel_custom config
    url_path: pose_estimation_panel
    sidebar_title: Pose Estimation Panel
    sidebar_icon: mdi:server
    module_url: /local/pose-estimation-panel.js
    config:
      # Data you want to make available to panel
      hello: world

# Add the relay MQTT device
light:
  - platform: mqtt
    # The topic that will be used to command the device
    name: "Relay device"
    state_topic: "devices/M5-relay-light/status"
    command_topic: "devices/M5-relay-light/switch"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
# Add the rgb MQTT light
# Json format
# {
#   "brightness": 255,
#   "color_mode": "rgb",
#   "color_temp": 155,
#   "color": {
#     "r": 255,
#     "g": 180,
#     "b": 200,
#     "c": 100,
#     "w": 50,
#     "x": 0.406,
#     "y": 0.301,
#     "h": 344.0,
#     "s": 29.412
#   },
#   "effect": "colorloop",
#   "state": "ON",
#   "transition": 2,
#   "white_value": 150
# }
  - platform: mqtt
    # The topic that will be used to command the device
    schema: json
    name: "rgb_light"
    state_topic: "devices/M5-rgb-light"
    command_topic: "devices/M5-rgb-light/set"
    brightness: true
    color_mode: true
    supported_color_modes: ["rgb"]


# Add the Jetson Nano
# TODO: Define data format
sensor:
  - platform: mqtt
    # The topic that will receive the poses that 
    # the jetson have recognized
    name: "Posture estimation"
    state_topic: "devices/pose-estimation/jetson-nano-1/postures-info"
    value_template: "{{ value_json.PoseLabel }}"
    availability:
      - topic: "devices/pose-estimation/jetson-nano-1/status"
    payload_available: "online"
    payload_not_available: "offline"
    
automation:
- id: one
  alias: "Toggle on light when the jetson Nano detects a raise of hand"
  trigger:
    - platform: state
      entity_id: jetson_nano
      to: "RaisedHand"
  action:
    - service: light.toggle
      target:
        entity_id: light
      

# This is the configuration of the UI
lovelace:
  # The UI is configured using this file
  # not the web tool
  mode: yaml

#
# Add-On for lovelace
#
  resources:
    # Adds the custom panel we created to home assistant
    - url: /local/pose-estimation-panel.js
      type: module

# Launch the MQTT broker on the server
mqtt:
  broker: 127.0.0.1

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
